In [53]:
from numpy import *
import numpy as np

In [7]:
a = array('i',[2, 4, -6, 8, 10])

In [8]:
a

array('i', [2, 4, -6, 8, 10])

In [14]:
for i in range(len(a)):
    print(a[i])

2
4
-6
8
10


In [15]:
for item in a:
    print(item)

2
4
-6
8
10


In [10]:
b = array('u', ['a', 'e', 'i', 'o', 'u'])

In [11]:
b

array('u', 'aeiou')

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
type(arr)

numpy.ndarray

**Project on Array :**

Q: Take numbers from the user and put them into an array, After that Ask the user about a number and search the position of that number

Answer:

In [25]:
n = int(input("How many numbers you want to give? "))

num = array('i', [])

for i in range(n):
    x = int(input("Enter a number: "))
    num.append(x)
    
print(num)


How many numbers you want to give? 4
Enter a number: 36534
Enter a number: 7452
Enter a number: 25354
Enter a number: 5235
array('i', [36534, 7452, 25354, 5235])


In [27]:
search = int(input("Enter a number for Search: "))

for j in num:
    if j == search:
        break
    
    j += 1
    
print(num.index(j))

Enter a number for Search: 7452
1


*Copying Array*

In [28]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = arr1

In [29]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5]


In [30]:
arr1[1] = 7

In [31]:
print(arr1)
print(arr2)

[1 7 3 4 5]
[1 7 3 4 5]


In [32]:
print(id(arr1))
print(id(arr2))

2385776621168
2385776621168


In [33]:
arr2 = arr1.view()

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 7 3 4 5]
[1 7 3 4 5]
2385776621168
2385776622208


In [34]:
arr1[2] = 9

print(arr1)
print(arr2)

[1 7 9 4 5]
[1 7 9 4 5]


In [35]:
arr2 = arr1.copy()

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[1 7 9 4 5]
[1 7 9 4 5]
2385776621168
2385776619568


In [36]:
arr1[3] = 8

print(arr1)
print(arr2)

[1 7 9 8 5]
[1 7 9 4 5]


*Playing with Matrices*

In [44]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [45]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
arr5.ndim

2

In [41]:
arr5.dtype

dtype('int32')

In [42]:
arr5.size

9

In [46]:
arr5.shape

(4, 3)

In [47]:
arr6 = arr5.flatten()

In [48]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
arr5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr5 + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
arr5 * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [54]:
#Making the Array into Matrix

mat = matrix(arr5)

In [55]:
mat

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [68]:
mat2 = matrix('1, 9, 3, 6 ; 4, 6, 8, 8 ; 7, 3, 9, 10')

In [69]:
mat2

matrix([[ 1,  9,  3,  6],
        [ 4,  6,  8,  8],
        [ 7,  3,  9, 10]])

In [60]:
mat.max()

12

In [62]:
mat.min()

1

In [65]:
mat3 = mat + mat2

In [66]:
mat3

matrix([[ 2, 11,  6],
        [ 8, 11, 14],
        [14, 11, 18],
        [22, 22, 22]])

In [71]:
mat4 = mat * mat2

In [72]:
mat4

matrix([[ 30,  30,  46,  52],
        [ 66,  84, 106, 124],
        [102, 138, 166, 196],
        [138, 192, 226, 268]])